### ISSUE TITLE
Menu "Search Analytics" is not showing for some administrators

### ISSUE THREAD

**Issue by fsarrio** [cornelRaiu/search-analytics#3]
I have two administrators accounts.
One can see the "Search Analytics" option in the menu, but for the other is not showing the menu.

I solved the problem changing one line inside the add_admin_menu() function inside the "admin/includes/class.stats.php" file. Line #98. My solution is not permanently, but works for me.

**Original line:**
add_submenu_page( 'index.php', __( 'Search Analytics', 'search-analytics' ), __( 'Search Analytics', 'search-analytics' ), $accepted_user_roles[0], __FILE__, array(

**Modified line:**
add_submenu_page( 'index.php', __( 'Search Analytics', 'search-analytics' ), __( 'Search Analytics', 'search-analytics' ), 'administrator', __FILE__, array(

I changed it because the $accepted_user_roles[0] doesn't have "0 position" in some cases.

**Debug of the variables used in this function:**

$this_user_role: 
Array ( [1] => administrator )

$accepted_user_roles: 
Array ( [1] => administrator )

$this->plugin_options['mwtsa_display_stats_for_role']:
Array ( [0] => administrator ) 

I hope it helps, thanks for creating the plugin.

**Comment by cornelRaiu** [comment]
@fsarrio Thank you for reporting this. I will adjust it for the next update.

**Comment by fsarrio** [comment]
Thanks cornelRaiu!

**Comment by cornelRaiu** [comment]
@fsarrio thank you again for reporting this issue.

**Comment by cornelRaiu** [comment]
@fsarrio I would really appreciate you [leaving a review and rating for the plugin](https://wordpress.org/support/plugin/search-analytics/reviews/#new-post). This is what really keeps it going.

**Comment by fsarrio** [comment]
Done!

**Comment by cornelRaiu** [comment]
@fsarrio Thank you! What do you think I should do to make you change your review in a 5 stars one? What should I improve?

**Comment by fsarrio** [comment]
Give me some days and I will try to check all the functionalities again.

**Comment by cornelRaiu** [comment]
@fsarrio Thank you! Looking forward to seeing your findings and persuading you to change it to a 5 stars :)
