### ISSUE TITLE
Filter by date is showing the information of the next day

### ISSUE THREAD

**Issue by fsarrio** [cornelRaiu/search-analytics#4]
The filter by date is showing +1 day information.

Example:

If I filter by the date 19th january 2021 the list shows the terms of the next day, 20th january 2021.

![image](https://user-images.githubusercontent.com/11427311/105852937-66190f80-5fe5-11eb-894f-dfcc1b697ff6.png)

![image](https://user-images.githubusercontent.com/11427311/105853012-80eb8400-5fe5-11eb-8bb0-0d4501b388f2.png)

**Comment by cornelRaiu** [comment]
@fsarrio I can no longer replicate this issue. Can you please confirm?
