### ISSUE TITLE
search bar shows results after 20 secs

### ISSUE THREAD

**Issue by IoanPaul** [cornelRaiu/search-analytics#6]
Hello, I have the fallowing problem - I've been using your plugin for almost 5 mounths, with no problem until the last WordPress update (6.01), since the update the search bar shows results after 20 secs. If you need the site to check or other infos, pls let me know.

**Comment by cornelRaiu** [comment]
Hi @IoanPaul ,

Can you try to disable the plugin and see if that solves the issue?

I am not seeing problems on any of my 10+ websites all being on WP 6.0.1.

Let me know.

**Comment by IoanPaul** [comment]
all done, ty for the reply. the problem was the search bar plugin

**Comment by cornelRaiu** [comment]
@IoanPaul thanks for the update!

If you enjoy using my plugin, please add a review on the [WordPress page](https://wordpress.org/support/plugin/search-analytics/reviews/#new-post).

Also, if you have suggestions or ideas on how to improve the plugin, you may open new issues here on GitHub.

Thanks!
